# 异常处理

当程序中的某但代码出现错误时，程序会将异常抛出，python解释器会获取异常并处理，一般处理的方式是程序异常退出并打印异常  
为防止代码一出现错误就强行结束而引入异常处理机制，当出现异常后自定义处理方式，处理完后程序继续执行

语法格式：  
```python
try:
    '可能出现错误的代码'
    pass
except Exception as e:
    '''
    出现异常时运行
    except可以捕获代码出现的异常， except之后加要捕获的异常类型
    Exception可以接收所有类型异常，其他具体类型异常查看官方文档
    as e 就是为Exception起一个别名
    '''
    pass
else:
    '没出现异常时运行'
    pass
finally:
    '有没有异常都会执行'
    pass
```

`try` 可以和其他三个关键字自由组合使用

向上抛出异常：
```python
try:
    pass
except Exception:
    '''
    通过 raise 关键字将异常抛给向上一级
    函数的上一级是调用端
    全局的上一级是python解释器
    '''
    raise
```

自定义异常类：
```python
class A(Exception):
    pass
```

抛出自定义异常：  
比如自定义异常是用户输入的数大于3
```python
a = int(input('输入一个小于3的数'))
try:
    
    if a >= 3:
        raise myException()
except myException:
    pass
# 自己抛出，自己捕获。自产自销
```
